### ISSUE TITLE
rxtx - cvs head

### ISSUE THREAD

**Issue by neophob** [arduino/RXTX#1]
hey guys

I also use the rxtx library for my project. I use the latest CVS head of the library and applied some fixes from the rxtx bugzilla site. I also patched the library for low latency, more details can be found here: http://neophob.com/2011/04/serial-latency-teensy-vs-arduino/

And it looks like your tree is screwed, check all the java files in the Rxtx/src directory for example.

my rxtx brach is here: https://github.com/neophob/librxtx 

what do you think about replace the arduino default librxtx with this`?

**Comment by moberhuber** [comment]
Can this issue be closed, since it looks like the low latency patch from neophob has been applied on Jan 13, 2013: See https://github.com/arduino/RXTX/commit/37fad90c51dcddfaae540a9398a727ef9a85011d
